### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by sindhu-ku** [sindhu-ku/noda#3]
### Discussed in https://github.com/sindhu-ku/noda/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **sindhu-ku** July 27, 2023</sup>
Big goals:
- [ ] Toy framework
- [ ] Different/faster way to treat systematics?
- [x] Add NMO
- [x] Nevents as free parameters
- [x] Add geoneutrino
- [ ] Add atmospheric oscillations

Computing:
- [x] Parallelize Bayesian
- [ ] Write Bayesian results in text file
- [x] iMinuit in addition to grid scan
- [ ] Add cos theta to positron energy shift

Cross-checks:
- [ ] sin2_th12 jumps
- [ ] Effect of binning
- [x] Check stat-only bayesian for 20 years, should not be weird
- [ ] Cov matrices check with Steven

Bug fixes:
- [x] fix command line options

Bayesian:
- [ ] low statistics problem</div>
